### ISSUE TITLE
feat: Publish Helm Chart

### ISSUE THREAD

**Issue by apricote** [hetznercloud/csi-driver#369]
Some use-cases require deeper customization of our deployment manifests. We should publish and provide a Helm chart for these users. The "simple" deployment manifests can then be generated from the Helm chart, by building it with the default values.

Example usecases that require deep customization:
- [x] non-standard kubelet config path, e.g. in k0s: #357 (in #516)
- [x] (non-)Default StorageClass https://github.com/hetznercloud/csi-driver/issues/369#issuecomment-1410005390 (in #500)
- [x] Image Pull Policy #358 (in #500)
- [x] Deploy `ServiceMonitor` and Grafana dashboard https://github.com/hetznercloud/csi-driver/pull/378#issuecomment-1440418738 (ServiceMonitor in #500, Grafana Dashboard moved to https://github.com/hetznercloud/csi-driver/issues/557)

**Comment by toabi** [comment]
That's a good plan. Another useful option for this would be to install it as non-default storage class.

**Comment by batistein** [comment]
@apricote you could use our helm chart as a starting point if you want. See: https://github.com/syself/charts/tree/main/charts/csi-hcloud

If I have some time in the next couple of weeks I will update it to the v2 version of the csi-driver.

**Comment by apricote** [comment]
The base Helm Chart is now in the repo and the remaining features from the list are available for pickup if anyone is interested :)

**Comment by apricote** [comment]
I opened https://github.com/hetznercloud/csi-driver/issues/557 for deploying the grafana dashboard in the chart. Closing this issue.
